# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzjSQtIGqm-StoAAu3ZSDq7qITe0wLOg
"""

import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("income-dataset.csv")

df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

df.replace('?', np.nan, inplace=True)

df.dropna(inplace=True)

df['income'] = df['income'].str.replace('.', '', regex=False)
df['income'] = df['income'].map({'<=50K': 0, '>50K': 1})

x = df.drop('income', axis=1)
y = df['income']

num_cols = x.select_dtypes(include=['int64', 'float64']).columns
cat_cols = x.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
])

model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print("Accuracy:", acc)

rep = classification_report(y_test, y_pred)

print("\nClassification Report:\n", rep)

df_encoded = pd.get_dummies(df, drop_first=True)

corr = df_encoded.corr()[['income']].sort_values(by='income', ascending=False)

print(corr.head(15))

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)