# -*- coding: utf-8 -*-
"""predict_featuregeneration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6dF8shhNnHhDJNWXRfXn-bL__10Ra8x
"""

import pandas as pd
import json
import pickle
import numpy as np

with open("model_fg.pkl", "rb") as f:
    model, scaler, selector = pickle.load(f)

file_path = input().strip()

with open(file_path, encoding='utf-8') as f:
    input_data = json.load(f)

input_df = pd.DataFrame([input_data])

input_df = input_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

input_encoded = pd.get_dummies(input_df)

input_encoded = input_encoded.reindex(columns=selector.feature_names_in_, fill_value=0)

input_selected = selector.transform(input_encoded)

input_scaled = scaler.transform(input_selected)

prediction = model.predict(input_scaled)[0]
prob = model.predict_proba(input_scaled)[0]

print(prediction, prob)